# Generated by Django 5.0.6 on 2024-05-19 12:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_result_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='uuid_num',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
