# Generated by Django 5.0.6 on 2024-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_blog_uuid_num_alter_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default='Blog title', max_length=100),
        ),
    ]
