# Generated by Django 5.0.6 on 2024-05-19 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_blog_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_description',
            field=models.TextField(default='blog description'),
        ),
    ]
