# Generated by Django 5.0.6 on 2024-05-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/profile/avatar1.png', upload_to='profile/'),
        ),
    ]
