# Generated by Django 5.0.6 on 2024-05-20 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_profile_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
